name: Run All Discord Bots

# on:
#   push:
#     branches: [ main ]
#   schedule:
#     - cron: "0 15 * * *"
#   workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Conservatory Bot
        run: npm run conservatory
        env:
          CONSERVATORY_DISCORD_WEBHOOK: ${{ secrets.CONSERVATORY_DISCORD_WEBHOOK }}

      - name: Run SUAGTFO Bot
        run: npm run suagtfo
        env:
          SUAGTFO_DISCORD_WEBHOOK: ${{ secrets.SUAGTFO_DISCORD_WEBHOOK }}

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: all-bot-logs
          path: |
            conservatory-quote-bot.log
            suagtfo-quote-bot.log

## How schedule works
#     ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday=0)
# │ │ │ │ │
# * * * * *
